### ISSUE TITLE
Add this to the package.json 

### ISSUE THREAD

**Issue by chrispois0n** [g-tecio/tlali-webeditor#1]
I need you to add this code to the package.json for deploying!

{
  "name": "tlali-web-editor",
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.3.6",
    "nuxt": "^2.3.4"
  }
}

**Comment by JaimeRdx** [comment]
It's already there
